some-proofs-only-work-without-autoTriggers.dfy(19,11): Info: Selected triggers: {x in a}
some-proofs-only-work-without-autoTriggers.dfy(20,11): Info: Selected triggers: {x in a[..|a|]}
some-proofs-only-work-without-autoTriggers.dfy(27,11): Info: Selected triggers: {x in a}
some-proofs-only-work-without-autoTriggers.dfy(28,11): Info: Selected triggers: {a[i]}
some-proofs-only-work-without-autoTriggers.dfy(31,11): Info: Selected triggers: {x in a[..3]}
some-proofs-only-work-without-autoTriggers.dfy(33,11): Info: Selected triggers: {x in a[..2]}
some-proofs-only-work-without-autoTriggers.dfy(20,11): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon28_Then
    (0,0): anon29_Then
    (0,0): anon4
    (0,0): anon30_Then
    (0,0): anon31_Then
    (0,0): anon7
some-proofs-only-work-without-autoTriggers.dfy(28,11): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon33_Then
    (0,0): anon34_Then
    (0,0): anon12
    (0,0): anon35_Then
    (0,0): anon36_Then
    (0,0): anon37_Then
    (0,0): anon17
some-proofs-only-work-without-autoTriggers.dfy(33,11): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon38_Then
    (0,0): anon39_Then
    (0,0): anon40_Then
    (0,0): anon22
    (0,0): anon41_Then
    (0,0): anon42_Then
    (0,0): anon25

Dafny program verifier finished with 0 verified, 3 errors
